<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="myrobot">

  <xacro:property name="base_width" value="0.32"/>
  <xacro:property name="base_len" value="0.32"/>
  <xacro:property name="wheel_radius" value="0.07"/>
  <xacro:property name="base_wheel_gap" value="0.007"/>
  <xacro:property name="wheel_separation" value="0.30"/>
  <xacro:property name="wheel_joint_offset" value="0.07"/>
  

  <xacro:property name="caster_wheel_radius" value="${wheel_radius/2}"/>
  <xacro:property name="caster_wheel_mass" value="0.002"/>
  <xacro:property name="caster_wheel_joint_offset" value="-0.104"/>

  <!--Color Properties-->
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <!--Interial macros-->
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}"/> 
    </inertial>
  </xacro:macro>

  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m / 12.0 * (d*d + h*h)}" ixy="0.0" ixz="0.0" iyy="${m / 12.0 * (w*w + h*h)}" iyz="0.0" izz="${m / 12.0 * (w*w + d*d)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${2.0*m*(r*r)/5.0}" ixy="0.0" ixz="0.0" iyy="${2.0*m*(r*r)/5.0}" iyz="0.0" izz="${2.0*m*(r*r)/5.0}"/>
    </inertial>
  </xacro:macro>

  <!--Base Footprint-->
  <link name="base_footprint">
    <xacro:box_inertia m="10" w="0.001" h="0.001" d="0.001"/>
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.05" />
        </geometry>
    </visual>
  </link>

  <!--Base link-->
  <link name="base_link">
    <xacro:box_inertia m="1" w="${base_len}" h="${base_width}" d="0.01"/>
    <visual>
      <geometry>
        <box size="${base_len} ${base_width} 0.1"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_len} ${base_width} 0.1"/>
      </geometry>
    </collision>
  </link>

  <!--base_link to base_footprint Joint-->
  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius + 0.005}" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

  <!--Wheel link & joint macro-->
  <xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="0.01"/>
        </geometry>
        <material name="red"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="0.01"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="1" r="${wheel_radius}" h="0.01"/>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${wheel_joint_offset} ${((base_width/2)+base_wheel_gap)*reflect} -0.005" rpy="0 0 0"/>
    </joint>

  </xacro:macro>

  <!--Create Left & Right Wheel links/joints-->
  <xacro:wheel prefix="left" reflect="1"/>
  <xacro:wheel prefix="right" reflect="-1"/>

  <!--Caster Wheel Link-->
  <link name="caster_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:sphere_inertia m="1" r="${caster_wheel_radius}"/>
  </link>

  <!--Caster Wheel Joint-->
  <joint name="caster_wheel_joint" type="continuous">
    <axis xyz="0 1 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="${caster_wheel_joint_offset} 0 -${caster_wheel_radius+0.005}" rpy="0 0 0"/>
  </joint>

<!--left guide-->
<link name="left_guide">
  <xacro:box_inertia m="1" w="${base_len}" h="${base_width}" d="0.01"/>
  <visual>
    <geometry>
      <box size="0.5 0.01 0.05"/>
    </geometry>
  <link name="left_guide">
    <xacro:box_inertia m="1" w="${base_len}" h="${base_width}" d="0.01"/>
    <visual>
      <geometry>
        <box size="0.5 0.01 0.05"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.5 0.01 0.05"/>
      </geometry>
    </collision>
  </link>

  <!--left_guide to left_guide Joint-->
  <joint name="left_guide_joint" type="fixed">
    <origin xyz="-0.2 0.5 0.0" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="left_guide" />
  </joint>
    <material name="blue"/>
  </visual>
  <collision>
    <geometry>
      <box size="0.5 0.01 0.05"/>
    </geometry>
  </collision>
</link>

<!--left_guide to left_guide Joint-->
<joint name="left_guide_joint" type="fixed">
  <origin xyz="-0.2 0.15 0.06" rpy="0 0 0" />
  <parent link="base_footprint"/>
  <child link="left_guide" />
</joint>

<!--right guide-->
<link name="right_guide">
  <xacro:box_inertia m="1" w="${base_len}" h="${base_width}" d="0.01"/>
  <visual>
    <geometry>
      <box size="0.5 0.01 0.05"/>
    </geometry>
  <link name="right_guide">
    <xacro:box_inertia m="1" w="${base_len}" h="${base_width}" d="0.01"/>
    <visual>
      <geometry>
        <box size="0.5 0.01 0.05"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.5 0.01 0.05"/>
      </geometry>
    </collision>
  </link>

  <!--right_guide to right_guide Joint-->
  <joint name="right_guide_joint" type="fixed">
    <origin xyz="-0.2 0.5 0.0" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="right_guide" />
  </joint>
    <material name="blue"/>
  </visual>
  <collision>
    <geometry>
      <box size="0.5 0.01 0.05"/>
    </geometry>
  </collision>
</link>

<!--right_guide to right_guide Joint-->
<joint name="right_guide_joint" type="fixed">
  <origin xyz="-0.2 -0.15 0.06" rpy="0 0 0" />
  <parent link="base_footprint"/>
  <child link="right_guide" />
</joint>

<!--body guide-->
<link name="body_guide">
  <xacro:box_inertia m="1" w="${base_len}" h="${base_width}" d="0.01"/>
  <visual>
    <geometry>
      <box size="0.2 0.2 0.3"/>
    </geometry>
  <link name="body_guide">
    <xacro:box_inertia m="1" w="${base_len}" h="${base_width}" d="0.01"/>
    <visual>
      <geometry>
        <box size="0.2 0.2 0.3"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.2 0.2 0.3"/>
      </geometry>
    </collision>
  </link>

  <!--body_guide to body_guide Joint-->
  <joint name="body_guide_joint" type="fixed">
    <origin xyz="0 0 1" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="body_guide" />
  </joint>
    <material name="blue"/>
  </visual>
  <collision>
    <geometry>
      <box size="0.2 0.2 0.3"/>
    </geometry>
  </collision>
</link>0

<!--body_guide to body_guide Joint-->
<joint name="body_guide_joint" type="fixed">
  <origin xyz="0 0 0.2" rpy="0 0 0" />
  <parent link="base_footprint"/>
  <child link="body_guide" />
</joint>  

  <xacro:include filename="$(find myrobot)/urdf/myrobot_pluggin.xacro"/>

</robot>